"""empty message

Revision ID: acf249be5c0a
Revises: ff78d4e9fcb5
Create Date: 2023-02-14 09:17:25.505069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf249be5c0a'
down_revision = 'ff78d4e9fcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cart_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['item_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('cart_product_id_fkey', 'product', ['product_id'], ['item_id'])

    # ### end Alembic commands ###
